name: imwfan
title: imwfan - Software engineer, Full-Stack web developer, and indie hacker.
description: I’m imwfan, a software developer engineer based in Shenzhen, China. I love coding and travelling. Building something interesting and useful is my passion.
  Thiago Rossener.
tags:
  - blog
  - template
  - jekyll
  - theme
  - netlify
show_hero: false
menu:
  - title: Home
    url: /
  - title: About
    url: /about
  - title: Contact
    url: /contact
  - title: Feed
    url: /feed.xml
email: mlum1685540@gmail.com
# See: https://disqus.com/
disqus_username: disqus_username
# Contact Form Setting
# See: https://formspree.io/
formspree_form_id: formspree_form_id
